Iter9
Tomap-Tomap/metricsService pull request #11
Opened 2024-01-25 20:59 UTC by DarkOmap

2024-02-02 13:37 UTC, Nikscorp requested changes
Написал комментарии в ишью в pr

2024-02-02 13:37 UTC, Nikscorp commented on .gitignore
> +db.json
просматривай плиз сам pr перед отправкой, тут например гитхаб тебе подсвечивает, что в конце файла нет пустой строки

2024-02-02 13:37 UTC, Nikscorp commented on internal/agent/agent.go
> +			"Error on sending poll count",
где-то логи пишутся с маленькой буквы, где-то с большой. Выбери один вариант, обычно это заглавная буква

2024-02-02 13:37 UTC, Nikscorp commented on internal/compresses/gzip.go
> +func GetCompressJSON(m models.Metrics) ([]byte, error) {
compressed

2024-02-02 13:37 UTC, Nikscorp commented on internal/compresses/gzip.go
> +func GetCompressJSON(m models.Metrics) ([]byte, error) {
тут лучше принимать any

2024-02-02 13:37 UTC, Nikscorp commented on internal/handlers/handlers.go
> +		return models.Metrics{}, err
чтобы не создавать тут инстанс можно возвращать указатель

2024-02-02 13:37 UTC, Nikscorp commented on internal/logger/logger.go
> +	r.responseData.status = statusCode
вызов WriteHeader опционален. Его может не быть, если Write выдан раньше — нужно тоже проставлять в статус 200, чтобы его залакировать.

Советую посмотреть на реализацию траппера в chi/middleware

2024-02-02 13:37 UTC, Nikscorp commented on internal/logger/logger.go
> +		Log.Info("got incoming HTTP request",
если будет паника в хэндлере — это строка не отработает, поэтому логировать тут лучше в defer-е

2024-02-02 13:37 UTC, Nikscorp commented on internal/logger/logger.go
> +		responseData *responseData
лишний уровень вложенности, поля responseData можно добавить прямо сюда

2024-02-02 13:37 UTC, Nikscorp commented on internal/server/server.go
> +	syncCtx, cancel := context.WithCancel(context.Background())
почему тут Background?

2024-02-02 13:37 UTC, Nikscorp commented on internal/storage/storage.go
> +		return func() <-chan struct{} { return nil }, fmt.Errorf("write event not enable")
nil, fmt.Errorf...

2024-02-02 13:37 UTC, Nikscorp commented on internal/server/server.go
> +	GetWriteEventFunc() (func() <-chan struct{}, error)
тут что-то очень сложное происходит. Зачем все это?

Там нужно просто раз в интервал дампить в файл мапу с метриками. И вычитывать ее при старте. Все это можно инкапсулировать в Storage слое.

2024-02-04 15:52 UTC, DarkOmap commented on .gitignore
> +db.json
Впердь буду внимательнее, исправил

2024-02-04 19:25 UTC, DarkOmap commented on internal/agent/agent.go
> +			"Error on sending poll count",
Исправил

2024-02-04 19:27 UTC, DarkOmap commented on internal/compresses/gzip.go
> +func GetCompressJSON(m models.Metrics) ([]byte, error) {
Исправил

2024-02-04 19:28 UTC, DarkOmap commented on internal/compresses/gzip.go
> +func GetCompressJSON(m models.Metrics) ([]byte, error) {
Исправил

2024-02-05 09:31 UTC, DarkOmap commented on internal/handlers/handlers.go
> +		return models.Metrics{}, err
Сделал. В целом есть какие-то правила по выбору возвращаемого типа? Ориентироваться на это? https://go.dev/wiki/CodeReviewComments#receiver-type

2024-02-05 10:50 UTC, DarkOmap commented on internal/logger/logger.go
> +	r.responseData.status = statusCode
Добавил из траппера проверку на запись заголовка

2024-02-05 10:50 UTC, DarkOmap commented on internal/logger/logger.go
> +		Log.Info("got incoming HTTP request",
Добавил defer

2024-02-05 10:51 UTC, timupk commented on internal/logger/logger.go
> +		responseData *responseData
удалил responseData, добавил в loggingResponseWriter поля code и bytes

2024-02-05 20:13 UTC, DarkOmap commented on internal/server/server.go
> +	syncCtx, cancel := context.WithCancel(context.Background())
Переделал логику, данный контекст больше не использую

2024-02-05 20:14 UTC, DarkOmap commented on internal/storage/storage.go
> +		return func() <-chan struct{} { return nil }, fmt.Errorf("write event not enable")
Передала логику работы сервера. Этой функции больше нет

2024-02-05 20:14 UTC, DarkOmap commented on internal/server/server.go
> +	GetWriteEventFunc() (func() <-chan struct{}, error)
Перенёс запись и чтения из файла в слой storage

2024-02-07 21:59 UTC, Nikscorp commented on internal/handlers/handlers.go
> +		return models.Metrics{}, err
rule of a thumb — если нет четкого понимания зачем делать иное — возвращай указатель.

Саму структуру правильней возвращать когда ты заведомо знаешь, что в структуре у тебя будет мало полей и ты хочешь сэкономить на уровне индерекции и / или копировании. Например time / coord и т.п. вещи

2024-02-07 22:09 UTC, Nikscorp approved these changes
Хорошая работа над ошибками.

Работа принята.

Перед следующим спринтом также делительно исправить оставленные замечания, они небольшие.

2024-02-07 22:09 UTC, Nikscorp commented on internal/logger/logger.go
> +			Log.Info("got incoming HTTP request",
тут уже скорее Sending HTTP response.

В целом хорошая идея при получении реквеста логировать событие реквеста, а когда завершили обработку логировать событие респонса

2024-02-07 22:09 UTC, Nikscorp commented on internal/logger/logger.go
> +func LogBadRequest(handlerName, uri string, err error) {
не думаю, что это хорошая идея выделять такие вещи  отельные функции, тем более в пакете логгера

2024-02-07 22:09 UTC, Nikscorp commented on internal/storage/storage.go
> +		ms.producer.WriteInFile(ms)
лучше дописывать только текущее "событие" обновление метрики. То есть ее текущее значение. И при чтении файла прокручивать все такие события и составлять мапу.

Каждый раз записывать в файл все значения может быть долго

2024-02-10 14:51 UTC, DarkOmap commented on internal/logger/logger.go
> +			Log.Info("got incoming HTTP request",
Добавил логирование реквеста

2024-02-10 15:11 UTC, DarkOmap commented on internal/logger/logger.go
> +func LogBadRequest(handlerName, uri string, err error) {
Перенёс логирование ошибок в мидлвару

2024-02-10 21:42 UTC, DarkOmap commented on internal/storage/storage.go
> +		ms.producer.WriteInFile(ms)
Переделал

2024-02-11 13:15 UTC, merged