Iter18
Tomap-Tomap/metricsService pull request #20
Opened 2024-04-21 15:11 UTC by Tomap-Tomap

2024-04-21 15:16 UTC, Tomap-Tomap commented
Если честно не особо осознал, что необходимо сделать в этом спринте.
Я сохранил профили профилирования, больше всего жрет памяти сжатие и разжатые данных, что тут оптимизировать не особо понятно.
gofmt и goimports уже встроены в IDE и не совсем понятно, что тут форматировать.
Комментарии я добавил, но основные пакеты находят в internal и они не отображаются в godoc.
Аналогично и с примерами, я добавил пример для обработчика update, но мне кажется, что всё это как-то криво-косо. Может быть нужно сделать swagger описание?

2024-04-23 12:07 UTC, timupk commented
Решил добавит swagger описание, добавил ендпоинт для просмотра описания.

2024-04-24 20:20 UTC, Nikscorp commented
А где result.pprof и diff между ними?

В задании я вижу 3 пунтка:

> Используя профилировщик pprof, сохраните профиль потребления памяти вашим проектом в директорию profiles с именем base.pprof.
> Изучите полученный профиль, определите и исправьте неэффективные части вашего кода.
> Повторите пункт 1 и сохраните новый профиль потребления памяти в директорию profiles с именем result.pprof.

2024-04-24 20:23 UTC, Nikscorp requested changes
оставил замечания

2024-04-24 20:23 UTC, Nikscorp commented on .github/workflows/mertricstest.yml
> -        if: |
а почему исправляется yml файл с CI тестами и это считается нормой? Все что тут описано — должно у тебя проходить

2024-04-24 20:23 UTC, Nikscorp commented on cmd/server/example_test.go
> +func Example() {
честно говоря не очень похоже на выполнение задания "Добавьте примеры работы с эндпоинтами практического трека".

Есть же и другие хэндлеры и непонятно почему функция называется просто example без указания конкретного хэнддера.
Btw, чтобы здесь не добавлять моки, ты можешь вставить просто пример работы. Не обязательно чтобы этот example проходил как тест (с output-ом)

2024-04-24 20:23 UTC, Nikscorp commented on internal/agent/agent.go
> +		go worker(egCtx, jobs)
зачем тут понадобились воркеры? Почему они запускаются вне errgroup-ы?

2024-05-02 22:50 UTC, Tomap-Tomap commented on .github/workflows/mertricstest.yml
> -        if: |
Убрал потому что ci тесты запускаются только для веток до 14 номера. Соответственно для ветки iter18 тесты не запускаются.
Вернул.

2024-05-02 22:55 UTC, Tomap-Tomap commented on cmd/server/example_test.go
> +func Example() {
Вынес хэндлеры из internal (чтобы примеры отображались в godoc). Добавил для них examples.

2024-05-02 22:56 UTC, Tomap-Tomap commented on internal/agent/agent.go
> +		go worker(egCtx, jobs)
Воркеры появились из 15 инкремента. Убрал.

2024-05-06 00:03 UTC, Nikscorp approved these changes
Замечания исправлены, ставлю аппрув

2024-05-06 18:29 UTC, merged