Iter20
Tomap-Tomap/metricsService pull request #21
Opened 2024-05-06 18:57 UTC by Tomap-Tomap

2024-05-15 00:44 UTC, Nikscorp requested changes
Оставил замечания в комментариях к pr

2024-05-15 00:44 UTC, Nikscorp commented on internal/logger/logger.go
> +	if version == "" {
jfyi в 1.22 это можно сделать в одну строку через cmp.Or

2024-05-15 00:44 UTC, Nikscorp commented on internal/logger/logger.go
> +func DisplayBuild(version, date, commit string) {
не уверен что это правильно помещать в пакет логгера, тут у нас все же обычная печать, я бы оставил в main-е

2024-05-15 00:44 UTC, Nikscorp commented on internal/osexitcheck/osexitcheck.go
> +			return true
нужно ли обходить в глубину что-то вне пакета main и функции main?

2024-05-15 00:44 UTC, Nikscorp commented on internal/osexitcheck/testdata/pkg1/pkg1.go
> +	os.Exit(0) // want "use os.Exit"
в задании было все же 

Напишите и добавьте в multichecker собственный анализатор, запрещающий использовать **прямой вызов os.Exit в функции main пакета main**

А тут и пакет и функция другие, так что тут линтер срабатывать не должен. Стоит поправить и добавить тест на положительный / отрицательный сценарии

2024-05-15 00:44 UTC, Nikscorp commented on staticcheck.conf
> +initialisms = []
не хватает empty newline-а в конце файла

2024-05-15 00:44 UTC, Nikscorp commented on cmd/server/main.go
> +	buildVersion string
следует добавить комментарий / sh скрипт / Makefile демонстрирующий сборку с нужными флагами

2024-05-15 11:13 UTC, Tomap-Tomap commented on internal/logger/logger.go
> +	if version == "" {
Обновил ci из шаблона, обновил go.mod для поддержки 1.22 воспользовался cmp.Or

2024-05-15 11:13 UTC, Tomap-Tomap commented on internal/logger/logger.go
> +func DisplayBuild(version, date, commit string) {
Перенёс функцию в майн

2024-05-15 11:14 UTC, Tomap-Tomap commented on internal/osexitcheck/osexitcheck.go
> +			return true
Неправильно прочел задание, исправил.

2024-05-15 11:14 UTC, Tomap-Tomap commented on internal/osexitcheck/testdata/pkg1/pkg1.go
> +	os.Exit(0) // want "use os.Exit"
Неправильно прочел задание, исправил. Добавил положительные и отрицательные тесты

2024-05-15 11:14 UTC, timupk commented on staticcheck.conf
> +initialisms = []
Добавил

2024-05-15 11:14 UTC, Tomap-Tomap commented on cmd/server/main.go
> +	buildVersion string
Добавил makefile-ы

2024-05-16 13:14 UTC, Nikscorp commented on internal/osexitcheck/testdata/pkg1/pkg1.go
> +	os.Exit(0) // want "use os.Exit"
Я бы все же оставил подход через testdata и под отрицательными кейфами имел в виду просто те, где линтер не срабатывает (функция не main), там достаточно было want просто не указывать

2024-05-16 13:15 UTC, Nikscorp approved these changes
Немного переуплотнил с тестами, но в целом все ок, задание принято

2024-05-16 14:44 UTC, merged