Iter25
Tomap-Tomap/metricsService pull request #24
Opened 2024-06-04 21:48 UTC by Tomap-Tomap

Добавил проверку по ip
Добавил поддержку grpc.
Переписал инициализацию агента и сервера.

2024-06-13 19:45 UTC, Bazys requested changes
1. GetAllGauge и GetAllCounter очень похожие функции, может сделать шаблонную функцию?
2. Очень часто не проверяешь ошибки
3. Не стал дублироовать одинаковые ошибки, подключай линтеры:
- errcheck
- goconst
- revive
4. Отформатируй код с помощью `gofumpt`
5. Принципиальных вопросов по коду в этих сринтах обычно не бывает и я не увидел, из за чего бы стоило заворачивать, поэтому давай доводить до совершенства по формальным признакам.

2024-06-13 19:45 UTC, Bazys commented on internal/server/server.go
> +type ServerOptionFunc func(*Server) error
снаружи это выгл]дит как `server.ServerOptionFunc` - масло масляное. Задумывайся на неймингом.

1. https://go.dev/blog/package-names
2. https://go.dev/doc/effective_go#names
3. https://google.github.io/styleguide/go/decisions.html

2024-06-13 19:45 UTC, Bazys commented on internal/client/client.go
> +		AddRetryCondition(func(r *resty.Response, err error) bool {
Параметр функции, названный `r`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `r` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-06-13 19:45 UTC, Bazys commented on internal/storage/memory_storage.go
>  		ms.producer.ClearFile()
функция может вернуть ошибку, а ты не проверяешь на это.

2024-06-17 09:50 UTC, Tomap-Tomap commented on internal/server/server.go
> +type ServerOptionFunc func(*Server) error
Прошелся ревайвом, поправил

2024-06-17 09:51 UTC, Tomap-Tomap commented on internal/client/client.go
> +		AddRetryCondition(func(r *resty.Response, err error) bool {
Прошелся ревайвом, поправил

2024-06-17 09:51 UTC, Tomap-Tomap commented on internal/storage/memory_storage.go
>  		ms.producer.ClearFile()
Добавил проверки, правда не совсем уверен, что я верно перехватываю ошибки defer функций

2024-06-17 09:55 UTC, Tomap-Tomap commented
> 1. GetAllGauge и GetAllCounter очень похожие функции, может сделать шаблонную функцию?

Честно говоря не совсем понимаю, как тут применить шаблонную функцию не переделывая всю модель целиком. Приравнял типы Gauge и Counter к интерфейсу Stringer, что позволило объединить в одну функцию, но что-то мне кажется, что это как-то неправильно.

По поводу остального, прошелся линтерами и форматером

2024-06-19 09:02 UTC, merged