Iter5
Tomap-Tomap/metricsService pull request #7
Opened 2023-12-28 15:09 UTC by DarkOmap

It is completed tasks for sprint 1

2023-12-30 12:06 UTC, Nikscorp requested changes
Оставил несколько замечаний

2023-12-30 12:06 UTC, Nikscorp commented on cmd/agent/flag.go
> +func parseFlags() {
всю работу с флагами лучше вынести в отдельный пакет

2023-12-30 12:06 UTC, Nikscorp commented on cmd/agent/flag.go
> +var flagRunAddr string
скорее это `listenAddr`

2023-12-30 12:06 UTC, Nikscorp commented on cmd/agent/main.go
> +	for {
в cmd не должно быть никакой сложной логики, только инициализация структур и запуск чего-то из внешнего пакета.

Остальное лучше вынести в internal

2023-12-30 12:06 UTC, Nikscorp commented on go.mod
> +go 1.21.5
лучше просто 1.21. Минорную версию не стоит ставить в go.mod

2023-12-30 12:06 UTC, Nikscorp commented on cmd/agent/main.go
> +		if timeToPush == reportInterval {
подучишься если `reportInterval` не делится без остатка на `pollInterval` этот код никогда не выполнится?

Вообще не очень понятно почему тут один общий цикл, а не 2 конкурентно работающих цикла

2023-12-30 12:06 UTC, Nikscorp commented on cmd/agent/main.go
> +				panic(err.Error())
паниковать при любой ошибке это плохо, лучше просто логировать ошибку и продолжать работать в подобных случаях

2023-12-30 12:06 UTC, Nikscorp commented on internal/client/client.go
> +		return errors.New("status not OK")
лучше fmt.Errorf и вставлять в сообщение об ошибке какой статус был получен

2023-12-30 12:06 UTC, Nikscorp commented on internal/handlers/handlers.go
> +var ms storage.MemStorage
глобальные переменные это плохо, почему бы не сделать это полем структуры

2023-12-30 12:06 UTC, Nikscorp commented on internal/handlers/handlers.go
> +func init() {
Аналогично если ms будет в структуре никой init нам будет не нужен, его использовать не рекомендуется

2023-12-30 12:06 UTC, Nikscorp commented on internal/memStats/memStats.go
> +package memstats
имя файла в camelCase

2023-12-30 12:06 UTC, Nikscorp commented on internal/memStats/memStats.go
> +var ms runtime.MemStats
снова глобальная переменная

2023-12-30 12:06 UTC, Nikscorp commented on internal/memStats/memStats.go
> +	val := reflect.ValueOf(ms)
рефлексия тут — это выстрел в ногу.

при расширении структуры `runtime.MemStats`, тебе придется добавлять новые значения в `isForServer` —такой код сложно читать и поддерживать. Лучше перечислить нужные значения руками

2023-12-30 12:06 UTC, Nikscorp commented on go.mod
> +require (
как будто не выполнялся go mod tidy

2023-12-30 12:06 UTC, Nikscorp commented on internal/handlers/handlers.go
> +func all(res http.ResponseWriter, req *http.Request) {
в задании кажется нет этого хэндлера. Но если делать что-то такое, лучше использовать html template из стандартной библиотеки go.

А еще лучше возвращать просто json)

2023-12-30 12:06 UTC, Nikscorp commented on internal/client/client.go
> +func init() {
зачем тут init?

2023-12-30 12:06 UTC, Nikscorp commented on internal/storage/storage.go
> +func (m *MemStorage) GetData() []dataResult {
возвращать приватные типо плохо, пользователь пакета может захотеть прикопать значение в структуру и без костылей это сделать не сможет

2023-12-30 12:06 UTC, Nikscorp commented on internal/storage/storage.go
> +func ParseGauge(g string) (gauge, error) {
аналогично, возвращаем приватный тип

2023-12-30 12:06 UTC, Nikscorp commented on internal/storage/storage.go
> +	GaugeType = iota
enum-ы лучше делать типизированными кастомные типом.

```
type MetricsType int


const (
    GaugeType MetricsType = iota
    CounterType
)
```

2023-12-30 12:06 UTC, Nikscorp commented on internal/storage/storage.go
> +type Typer interface {
совсем не уверен, что следует делать counter и gauge одним интерфейсом.

Так код становится только сложнее, я бы сделал 2 разных метода для Counter-a и Gauge.

Set / Get и Add / Get

Так и разную семантику метрик будет видно лучше (сейчас метод AddValue где-то делает Add, а где-то Set)

2023-12-30 16:25 UTC, DarkOmap commented on internal/handlers/handlers.go
> +func all(res http.ResponseWriter, req *http.Request) {
![image](https://github.com/DarkOmap/metricsService/assets/51964383/080828ee-d34f-4a3d-bd5c-0fc8e6d4a8f4)

Я как-то неправильно интерпретировал эту строчку в задании? Так бы с радостью возвращал бы JSON)

2023-12-30 19:37 UTC, Nikscorp commented on internal/handlers/handlers.go
> +func all(res http.ResponseWriter, req *http.Request) {
да, мой косяк, не увидел этого в задании.

Тогда справедлив комментарий только про использование https://pkg.go.dev/html/template

Впрочем, раз про него не рассказывали в занятиях, пока можно пропустить

2024-01-09 23:09 UTC, Nikscorp requested changes
Привет!

Хорошая работа, код стал лучше.
Оставил еще несколько замечаний, прошу их исправить.

Также прошу отвечать на каждый комментарий после исправления — это сильно упрощает проверку

2024-01-09 23:09 UTC, Nikscorp commented on internal/client/client.go
> +	done := make(chan struct{})
канал тут просто создается и с ним ничего не происходит. Зачем тогда канал?

Я бы сделал так:
- завел waitgroup-у на 2 горутины
- завел бы контекст завершающийся по sigint / sigterm (через signal.NotifyContext)
- в каждой горутине читал бы в select-е `ctx.Done()` и `time.After` по нужному таймауту
- прикидывал бы контекст в функции дергающие http ручки
- в конце функции делал бы `wg.Wait`
- в горутинах defer `wg.Done()`

2024-01-09 23:09 UTC, Nikscorp commented on internal/client/client.go
> +			pollCount++
тут потенциальный рейс, в одной горутине счетчик инкрементируется, в другой читается

2024-01-09 23:09 UTC, Nikscorp commented on internal/client/client.go
> +package client
почему пакет называется client, а не agent? В client я бы ожидал увидеть только функции / методы дергающие внешние ручки, а тут логика агента еще.

Можно или разделить на 2 пакета или переименовать (правильней как будто разделить)

2024-01-09 23:09 UTC, Nikscorp commented on internal/client/client.go
> +			return err
ошибки лучше всегда врапать, чтобы не терялся контекст https://go.dev/blog/go1.13-errors

2024-01-09 23:09 UTC, Nikscorp commented on internal/storage/storage.go
> +type MemStorage struct {
тут возможен рейс при конкурентном доступе к мапам

2024-01-09 23:09 UTC, Nikscorp commented on internal/storage/storage.go
> +type Repositories interface {
в go интерфейсы принято объявлять в месте их использования — https://go.dev/wiki/CodeReviewComments#interfaces

2024-01-10 15:26 UTC, DarkOmap commented on internal/client/client.go
> +	done := make(chan struct{})
По правде впервые сталкиваюсь с контекстами. Я сделал, но стойкое ощущение, что что-то не так

2024-01-10 15:26 UTC, DarkOmap commented on internal/client/client.go
> +			pollCount++
Добавил мьютекс

2024-01-10 15:26 UTC, timupk commented on internal/client/client.go
> +package client
Разбил на пакеты: client и agent

2024-01-10 15:27 UTC, timupk commented on internal/client/client.go
> +			return err
Сделал

2024-01-10 15:29 UTC, DarkOmap commented on internal/storage/storage.go
> +type MemStorage struct {
Добавил RW мьютекс как тут https://go.dev/blog/maps
Только меня смущает клонирование мапы в GetAllCounter и GetAllGrauge. Я же правильно понимаю, что при больших данных, каждый пользователь будет достаточно продолжительно ждать друг друга?
Может лучше использовать мапу из пакета sync?

2024-01-10 15:29 UTC, DarkOmap commented on internal/storage/storage.go
> +type Repositories interface {
Перенёс интерфейс в пакет handlers

2024-01-11 09:07 UTC, Nikscorp commented on internal/storage/storage.go
> +type MemStorage struct {
клонирование мапы тут норм, вредил в ней когда либо будет столько данных, чтобы это хоть как-то ощутимо влияло на перфоманс

> Может лучше использовать мапу из пакета sync?

Не думаю, что в данном кейсе она подойдет лучше, я бы оставил как есть

2024-01-11 10:12 UTC, Nikscorp requested changes
Привет!

Хорошая работа над замечаниями, есть еще несколько на исправление, думаю еще одной итерации хватит, чтобы принять работу.

2024-01-11 10:12 UTC, Nikscorp commented on cmd/agent/main.go
> +	listenAddr, reportInterval, pollInterval := parameters.ParseFlagsAgent()
кажется, что правильней, чтобы здесь возвращалась структура, вдруг флагов станет больше?

2024-01-11 10:12 UTC, Nikscorp commented on cmd/server/main.go
> +	flagRunAddr := parameters.ParseFlagsServer()
несмотря на то, что параметр пока один, лучше все равно возвращать структуру

2024-01-11 10:12 UTC, Nikscorp commented on internal/agent/agent.go
> +	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
все же не stop, а cancel

2024-01-11 10:12 UTC, Nikscorp commented on internal/agent/agent.go
> +				sendReport(&ms, ctx, listenAddr, pollCount, &mutex)
прикидывать в функцию мьютекс выглядит не очень. Это верный признак того, что Run и sendReport должны быть методами одной структуры

2024-01-11 10:12 UTC, Nikscorp commented on internal/client/client.go
> +func SendGauge(ctx context.Context, addr, name, value string) error {
client тоже лучше сделать структурой, а функции — методами. В конструкторе инициализировать его адресом, чтобы не передавать каждый раз в функцию

2024-01-11 10:12 UTC, Nikscorp commented on internal/client/client.go
> +			return fmt.Errorf("push error memstats index %d: %w", idx, err)
слово error в сообщении об ошибке лишнее, понятно что это ж и так ошибка

2024-01-11 10:12 UTC, Nikscorp commented on internal/agent/agent.go
> +		log.Print(err.Error())
а вот в логе все же стоит делать Printf и помимо самой ошибки писать что произошло, вот тут как раз слово Error нужно.

`log.Printf("Error on sending counter: %s", err)`

2024-01-11 10:12 UTC, Nikscorp commented on internal/handlers/handlers.go
> +type repositories interface {
а почему repositories во множественном числе?

2024-01-11 10:12 UTC, Nikscorp commented on internal/agent/agent.go
> +	pollCount := 0
ее как будто правильней сделать атомиком и убрать мьютекс

2024-01-11 10:12 UTC, Nikscorp commented on internal/memstats/memstats.go
> +func GetMemStatsForServer(ms *runtime.MemStats) (stringsMS []StringMS) {
можно сразу преаллоцировать нужную память для stringsMS

2024-01-11 10:12 UTC, Nikscorp commented on internal/storage/storage.go
> +	gauges struct {
лучше не использовать анонимные структуры нигде кроме тестов

2024-01-11 15:47 UTC, timupk commented on cmd/agent/main.go
> +	listenAddr, reportInterval, pollInterval := parameters.ParseFlagsAgent()
Сделал структуру AgentParameters

2024-01-11 15:47 UTC, DarkOmap commented on cmd/server/main.go
> +	flagRunAddr := parameters.ParseFlagsServer()
Сделал

2024-01-11 15:47 UTC, DarkOmap commented on internal/agent/agent.go
> +	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
Сделал

2024-01-11 15:47 UTC, DarkOmap commented on internal/agent/agent.go
> +				sendReport(&ms, ctx, listenAddr, pollCount, &mutex)
Сделал структуру agent с методами Run() и sendReport()

2024-01-11 15:48 UTC, DarkOmap commented on internal/client/client.go
> +func SendGauge(ctx context.Context, addr, name, value string) error {
Сделал структуру Agent

2024-01-11 15:48 UTC, DarkOmap commented on internal/client/client.go
> +			return fmt.Errorf("push error memstats index %d: %w", idx, err)
Сделал

2024-01-11 15:50 UTC, DarkOmap commented on internal/agent/agent.go
> +		log.Print(err.Error())
Передал на printf

2024-01-11 15:50 UTC, DarkOmap commented on internal/handlers/handlers.go
> +type repositories interface {
Переименовал в repository

2024-01-11 15:51 UTC, DarkOmap commented on internal/agent/agent.go
> +	pollCount := 0
Добавил поле-атомик pollCount в структуру Agent

2024-01-11 15:54 UTC, DarkOmap commented on internal/memstats/memstats.go
> +func GetMemStatsForServer(ms *runtime.MemStats) (stringsMS []StringMS) {
Преаллоцировал 27 элементов. Может тогда лучше массив использовать, а не слайс?

2024-01-11 15:55 UTC, DarkOmap commented on internal/storage/storage.go
> +	gauges struct {
Добавил структуры gauges и counters

2024-01-15 20:18 UTC, Nikscorp commented on internal/memstats/memstats.go
> +func GetMemStatsForServer(ms *runtime.MemStats) (stringsMS []StringMS) {
нет, массивы используется крайне редко, нужно учитывать, что они еще копироваться будут при передаче по значению и в основном их используют только когда данное свойство может помочь

2024-01-15 20:26 UTC, Nikscorp approved these changes
Хорошая работа над замечаниями!

Оставил еще несколько ишью, но они некритичные, так что работу принимаю.
Будет здорово если перед мерджем их тоже поправишь.

Работа принята, посылать на ревью ее повторно не надо. Как исправишь замечания и тесты пройдут — можно мерджить)

2024-01-15 20:26 UTC, Nikscorp commented on internal/client/client.go
> +	client := resty.New()
не уверен, что хорошо пересоздавать клиента на каждый запрос.
Можно конечно внимательно прочитать доку resty (я с ним работал мало), но почти уверен, что эффективней будет прикапывать инстанс клиента в структуру и получать пользу от keep-alive tcp соединений, экономя время на каждый запрос

2024-01-15 20:26 UTC, Nikscorp commented on internal/handlers/handlers.go
> +		v, err := storage.ParseGauge(chi.URLParam(req, "value"))
не очень удобно делать parse, а затем set. Кажется это можно объединить в единственный метод. Для `counter-а` аналогично

2024-01-15 20:26 UTC, Nikscorp commented on internal/memstats/memstats.go
> +	stringsMS := make([]StringMS, 0, 27)
честно говоря append-ы я бы вообще заменил на инициализацию слайса элементами

2024-01-17 10:00 UTC, merged